[package]
name = "dcc"
version = "0.5.1"
authors = ["David Pederson <dpederson@figure.com>", "Lee Duan <lduan@figure.com>"]
edition = "2018"

exclude = [
  "dcc.wasm",
  "checksums.txt",
]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
provwasm-std = { version = "1.1.0" }
cosmwasm-std = { version = "1.0.0", features = ["iterator"] }
cosmwasm-storage = { version = "1.0.0", features = ["iterator"] }
cw2 = "0.13.4"
schemars = "0.8.10"
semver = "1.0.13"
serde = { version = "1.0.143", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.32" }

[dev-dependencies]
provwasm-mocks = { version = "1.1.0" }
cosmwasm-schema = { version = "1.0.0" }
