FROM azul/zulu-openjdk:17-jre

ADD ./docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY ./service/build/libs/*.jar /service.jar

EXPOSE 5080/tcp 8080/tcp 443/tcp

ENTRYPOINT ["/bin/bash", "-c", "./docker-entrypoint.sh /service.jar"]
