FROM gradle:7.1.1-jdk11 AS build
RUN gradle --version && java -version
WORKDIR /app

# Only copy dependency-related files
COPY build.gradle.kts gradle.properties settings.gradle.kts buildSrc/build.gradle.kts /app/

# Only download dependencies
# Eat the expected build failure since no source code has been copied yet
RUN gradle clean build --no-daemon > /dev/null 2>&1 || true

# Copy all files
COPY service /app/service/
COPY database /app/database/
COPY buildSrc /app/buildSrc/
COPY .git /app/.git/
COPY build.gradle.kts gradle.properties settings.gradle.kts /app/
COPY CHANGELOG.md CODE_OF_CONDUCT.md CONTRIBUTING.md LICENSE README.md /app/

# Do the actual build
RUN gradle clean build --no-daemon

FROM openjdk:11-jre

COPY --from=build /app/service/build/libs/*.jar /service.jar

EXPOSE 8080/tcp

CMD java -jar /service.jar
