FROM openjdk:17-zulu

ADD ./docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY ./report/build/libs/*.jar /report.jar

EXPOSE 5080/tcp 8080/tcp 443/tcp

ENTRYPOINT ["/bin/bash", "-c", "./docker-entrypoint.sh /report.jar"]
