FROM openjdk:11-jre

ADD ./docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY ./report/build/libs/*.jar /report.jar

EXPOSE 5080/tcp 8080/tcp 443/tcp

ENTRYPOINT ./docker-entrypoint.sh /report.jar
