FROM openjdk:11-jre

ADD ./docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY ./service/build/libs/*.jar /service.jar

# download the opentelemetry java agent. To run with the agent, add -javaagent:/opentelemetry-javaagent.jar and any 
# other configuration properites to your JAVA_OPTS
RUN wget https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.9.1/opentelemetry-javaagent.jar

EXPOSE 5080/tcp 8080/tcp 443/tcp

ENTRYPOINT ./docker-entrypoint.sh /service.jar
