name: Build and Deploy

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

jobs:
  deploy:
    name: Build
    runs-on: [ linux, self-hosted ]
    env:
      NEXUS_USER: ${{ secrets.NEXUS_USER }}
      NEXUS_PASS: ${{ secrets.NEXUS_PASS }}
      BUILD_OFFSET: 2000
    steps:
      - name: Configure JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up shared actions
        uses: actions/checkout@v2
        with:
          repository: FigureTechnologies/shared-actions
          ref: v1
          token: ${{secrets.PAT}}
          path: shared-actions

      - name: Run ktlint
        run: |
          ./gradlew ktlint --parallel

      - name: Build
        run: |
          ./gradlew --console=plain --refresh-dependencies clean build -x test

      - name: Publish
        run: |
          ./gradlew publish -PartifactVersion=$DOCKER_BUILD_TAG

      - name: Build image
        uses: ./shared-actions/docker-image-action
        with:
          gcp_auth_json: ${{secrets.GCP_AUTH_JSON}}
          dockerfile: service/docker/Dockerfile
          context: service

      - name: Docker Tag and Push
        env:
          GCP_AUTH_JSON: ${{ secrets.GCP_AUTH_JSON }}
        run: |
          echo ${GCP_AUTH_JSON} | docker login -u _json_key --password-stdin https://$GAR_HOST

          docker tag $DOCKER_BASE_URL$REPO:$DOCKER_BUILD_TAG $DOCKER_BASE_URL$REPO:latest
          docker push $DOCKER_BASE_URL$REPO:latest

      - name: Deploy
        if: ${{ env.BRANCH == 'develop' }}
        uses: ./shared-actions/deploy-action
        with:
          deployment_path: './deployment.yaml'
          gcp_auth_json: ${{secrets.GCP_AUTH_JSON}}
          deployinator_auth_json: ${{secrets.DEPLOYINATOR_AUTH_JSON}}

  slack:
    name: Slack
    runs-on: [ linux, self-hosted ]
    if: always()
    needs: [ deploy ]
    steps:
      - name: Checkout Figure shared actions
        uses: actions/checkout@v2-beta
        with:
          repository: FigureTechnologies/shared-actions
          ref: v1
          token: ${{ secrets.PAT }}
          path: shared-actions

      - name: Notify via Slack
        uses: ./shared-actions/notify-slack-action
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENTS_WEBHOOK }}
        with:
          needs: ${{ toJSON(needs) }}
          emoji: ":kotlin:"
