name: Smart Contract Build and Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_lint:
    strategy:
      fail-fast: false
      matrix:
        sc:
          - smart-contract
          - smart-contract-sale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.sc }}
      - run: cargo build
        working-directory: ./${{ matrix.sc }}
      - run: cargo clippy --all-features
        working-directory: ./${{ matrix.sc }}

  test:
    strategy:
      fail-fast: false
      matrix:
        sc:
          - smart-contract
          - smart-contract-sale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.sc }}
      - run: cargo test
        working-directory: ./${{ matrix.sc }}
