name: Smart Contract Build and Test
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build_and_lint:
    strategy:
      fail-fast: false
      matrix:
        sc:
        - smart-contract
        - smart-contract-sale
    runs-on: figure-linux-standard
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: wasm32-unknown-unknown
        override: true
        components: clippy
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.sc }}
        workspaces: |
          ${{ matrix.sc }}
    - run: cargo build --target wasm32-unknown-unknown
      working-directory: ./${{ matrix.sc }}
    - run: cargo clippy --no-deps
      working-directory: ./${{ matrix.sc }}

  test:
    strategy:
      fail-fast: false
      matrix:
        sc:
        - smart-contract
        - smart-contract-sale
    runs-on: figure-linux-standard
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.sc }}
        workspaces: |
          ${{ matrix.sc }}
    - run: cargo test
      working-directory: ./${{ matrix.sc }}
